### ISSUE TITLE
Typo in .gitattributes?

### ISSUE THREAD

**Issue by airblade** [systemmonkey42/attribute-test#1]
I think there may be a typo in `.gitattributes`:

```diff
diff --git i/.gitattributes w/.gitattributes
index 20e5156..9d64a26 100644
--- i/.gitattributes
+++ w/.gitattributes
@@ -1,7 +1,7 @@
 
 [attr]base64     filter=base64 diff=base64 merge=base64
-[attr]reverse    filter=rev diff=rev nerge=rev
-[attr]indent     filter=clang-tidy diff=clang-tidy nerge=clang-tidy
+[attr]reverse    filter=rev diff=rev merge=rev
+[attr]indent     filter=clang-tidy diff=clang-tidy merge=clang-tidy
 
 *.1   base64
 *.2   reverse
```

Anyway, when I follow the instructions, `git status` reports that `bash.1` is modified (`git diff` reports no difference).  Is that correct?  I would have expected neither file to be modified.

**Comment by systemmonkey42** [comment]
Its been a long time since I referred to this repo.

These are my steps
```
$ git clone https://github.com/systemmonkey42/attribute-test
Cloning into 'attribute-test'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 17 (delta 6), reused 16 (delta 5), pack-reused 0
Receiving objects: 100% (17/17), 230.66 KiB | 3.34 MiB/s, done.
Resolving deltas: 100% (6/6), done.
$ cd attribute-test/
$ head -5  bash.1
QkFTSCgxKSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEdl
bmVyYWwgQ29tbWFuZHMgTWFudWFsICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICBCQVNIKDEpCgpOQU1FCiAgICAgICBiYXNoIC0gR05VIEJvdXJuZS1BZ2FpbiBT
SGVsbAoKU1lOT1BTSVMKICAgICAgIGJhc2ggW29wdGlvbnNdIFtjb21tYW5kX3N0cmluZyB8IGZp
bGVdCgpDT1BZUklHSFQKICAgICAgIEJhc2ggaXMgQ29weXJpZ2h0IChDKSAxOTg5LTIwMTggYnkg
$ ./install.sh
+ git config --local include.path ../.gitconfig
$ rm bash.1
$ git co -- .
$ git status
## main...origin/main
```
Comparing the "stage"/"index" to the "worktree", "stage" contains:
```
$ git show :./bash.1|head -5
QkFTSCgxKSAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEdl
bmVyYWwgQ29tbWFuZHMgTWFudWFsICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICBCQVNIKDEpCgpOQU1FCiAgICAgICBiYXNoIC0gR05VIEJvdXJuZS1BZ2FpbiBT
SGVsbAoKU1lOT1BTSVMKICAgICAgIGJhc2ggW29wdGlvbnNdIFtjb21tYW5kX3N0cmluZyB8IGZp
bGVdCgpDT1BZUklHSFQKICAgICAgIEJhc2ggaXMgQ29weXJpZ2h0IChDKSAxOTg5LTIwMTggYnkg
```
Work-tree contains:
```
$ head -5 bash.1
BASH(1)                                                General Commands Manual                                               BASH(1)

NAME
       bash - GNU Bourne-Again SHell
```
So, "git show" (which dumps the contents of the "stage") shows the file as base64 encoded in the repo, while "head" shows the file in its original format.

To really show what is going on, try

```
$ GIT_TRACE=2 git checkout -- bash.1
01:04:08.127296 git.c:439               trace: built-in: git checkout -- bash.1
01:04:08.127910 run-command.c:655       trace: run_command: base64
01:04:08.132673 run-command.c:655       trace: run_command: base64
01:04:08.139040 git.c:439               trace: built-in: git rev-parse --git-dir
01:04:08.140222 run-command.c:1551      run_processes_parallel: done
```
If you run it again...
```
$ GIT_TRACE=2 git checkout -- bash.1
01:04:10.639542 git.c:439               trace: built-in: git checkout -- bash.1
01:04:10.642338 git.c:439               trace: built-in: git rev-parse --git-dir
01:04:10.643516 run-command.c:1551      run_processes_parallel: done
```

This is part of the mystery.  I suspect GIT caches the "cleaned" file in the index (as opposed to the stage), so git "checkout" fetches a copy from the "store", cleans it, and saves the "clean" version in the "index" and the "working tree."

If you try to "stage" a "patch", it fails because the "stage" is a "smudged" version of the "index", so a DIFF between the working directory and the "index" is not usable against the "stage". (phew)

This also partly explains why changing the git config for "smudge" and "clean" doesn't seem to have an immediate effect.  You have to force a refresh of the "index"

eg,  after a fresh checkout, followed by "install.sh", the repo "might" not notice the files should be changed.
After "update-index"
```
$ GIT_TRACE=2 git update-index --really-refresh --force-write-index
01:12:26.641724 git.c:439               trace: built-in: git update-index --really-refresh --force-write-index
01:12:26.642287 run-command.c:655       trace: run_command: base64
bash.1: needs update
01:12:26.647769 run-command.c:655       trace: run_command: rev
bash.2: needs update
```
git status show correctly
```
$ git status
## main...origin/main
 M bash.1
 M bash.2
```

Also, git has a core function for checking attributes
```
$ git check-attr -a bash.1
bash.1: diff: base64
bash.1: merge: base64
bash.1: base64: set
bash.1: filter: base64
```

You could safely detect that a "merge" filter is set this way, and probably assume a patch will not apply (since the while file needs to be "smudged" on its way to the stage).

**Comment by airblade** [comment]
Thank you for the extra detail.

I haven't come across the idea of the index and the stage being different things.  I thought they were two names for the same thing.

Anyway, the manual page for `gitattributes` says that git can cache the output of text conversion but you have to opt in to it:

> Because text conversion can be slow, especially when doing a large number of them with `git log -p`, Git provides a mechanism to cache the output and use it in future diffs. To enable caching, set the "cachetextconv" variable in your diff driver’s config. For example:
>
>               [diff "jpg"]
>                       textconv = exif
>                       cachetextconv = true

As far as I understand, after setting up this repo `git status` should report no changes to `bash.1` and `bash.2`.  However it always says `bash.1` is modified (but not `bash.2`), no matter what I do.  Yet `git diff` produces empty output.

Never mind, the repo still illustrates clean and smudge nicely :)

**Comment by systemmonkey42** [comment]
> As far as I understand, after setting up this repo git status should report no changes to bash.1 and bash.2. However it always says bash.1 is modified (but not bash.2), no matter what I do. Yet git diff produces empty output.

That is correct, and is what I get.   If I had to guess, I'd might suggest that your "base64" could produce slightly different encoded output.

EG
```
$ git show :bash.1 | sha256sum
23c967bb5e013a6868bc0469ff45fb18d8405f7a01c0e5d4e4fbe02df5a071a0  -
$ base64 <  bash.1 | sha256sum
23c967bb5e013a6868bc0469ff45fb18d8405f7a01c0e5d4e4fbe02df5a071a0  -

If your "base64" produces different "encoded" output, it might explain the weirdness.

**Comment by airblade** [comment]
> If your "base64" produces different "encoded" output, it might explain the weirdness.

You're right:

```
$ git show :bash.1 | shasum -a 256
23c967bb5e013a6868bc0469ff45fb18d8405f7a01c0e5d4e4fbe02df5a071a0  -
$ base64 < bash.1 | shasum -a 256
9e800f51ae10a35edde57b6131a657b2bd38e4119e26de7222621721df0307b9  -
```
